services:
  app:
    image: cpc0816/ecommerce-app:latest
    container_name: ecommerce_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER:-admin}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - DB_NAME=${POSTGRES_DB:-ecommerce}
      - DB_PORT=5432
      - REDIS_HOST=redis
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: ecommerce_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB=${POSTGRES_DB:-ecommerce}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: ecommerce_redis
    networks:
      - app-network
    ports:
      - "6379:6379"

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge